language: node_js
node_js:
  - "6.9"
script:
  - "yarn run lint && yarn run test"
cache:
  yarn: true
  directories:
    - node_modules
    - "yarn run lint && yarn run test && yarn run webpack --config ./webpack.prod.config.js --progress"
